version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/PiggyAuctions-React"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/PiggyAuctions-REST"
    update_schedule: "daily"